# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
  - 
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displyName: Restore

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore'
  displyName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*test.csproj'
    arguments: '--no-restore'
  displyName: Test

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CostomerApi.csproj'
    arguments: '--configurarion $(buildConfiguration) --no-restore'
    modifyOutputpath: false
  displyName: Publish